sudo: required
services:
  - docker

before_install:
  - docker build -t sud2587/docker-react -f Dockerfile.dev .

script:
  - docker run sud2587/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-249299306880"
  bucket_path: "docker"
  on:
    branch: master
  access_key_d: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"